version: '3'

services:
  hyperpipe-frontend:
    image: hyperpipe-frontend
    build:
      context: .
      args:
        pipedapi: pipedapi.kavin.rocks
        api: hyperpipeapi.onrender.com
    container_name: hyperpipe-frontend
    restart: unless-stopped
    ports:
      - '8080:80'
